version: '3.8'

services:
  app:
    image: tesnime19/sql_comment_injection:latest  # Image partagée sur Docker Hub
    ports:
      - "8080:8080"                               # Mappe le port 8080 de l'hôte vers le conteneur
    environment:
      - FLASK_ENV=development                     # Active le mode développement (optionnel)
    restart: always                               # Relance le conteneur automatiquement en cas d'arrêt
